# Generated by Django 2.2.1 on 2019-05-01 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerTitle', models.TextField(max_length=150, verbose_name='Текст ответа')),
                ('selected', models.BooleanField(default=False, verbose_name='Выбрано')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionTitle', models.TextField(max_length=150, verbose_name='Текст вопроса')),
                ('answers', models.ManyToManyField(related_name='answers', to='api.Answer', verbose_name='Ответы')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testTitle', models.TextField(max_length=100, verbose_name='Название теста')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('questions', models.ManyToManyField(related_name='questions', to='api.Question', verbose_name='Вопросы')),
            ],
            options={
                'verbose_name': 'тест',
                'verbose_name_plural': 'тесты',
            },
        ),
    ]
