# Generated by Django 2.2.1 on 2019-05-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190505_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100, verbose_name='Название предмета')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=150, verbose_name='Название поста')),
                ('miniBody', models.TextField(max_length=150, verbose_name='Под заголовок')),
                ('body', models.TextField(max_length=700, verbose_name='Содержание')),
                ('author', models.TextField(max_length=100, verbose_name='Автор')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('subject', models.ManyToManyField(related_name='subject', to='api.Subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
