# Generated by Django 2.2.1 on 2019-05-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subject',
        ),
        migrations.AddField(
            model_name='subject',
            name='posts',
            field=models.ManyToManyField(related_name='posts', to='api.Post', verbose_name='Посты'),
        ),
    ]
