# Generated by Django 2.2.1 on 2019-05-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190505_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='subject_id',
            field=models.ManyToManyField(related_name='subject', to='api.Subject', verbose_name='Предмет'),
        ),
    ]
